version: '3'

services:
  redis:
    image: redis
    volumes:
      - redis-data:/data

  mongo:
    image: mongo
    ports:
      - '27017-27019:27017-27019'
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: '.'
    environment:
      - MONGO_URI='mongodb://mongo:27017/'
      - CELERY_BROKER_URL='redis://redis:6379/0'
    depends_on:
      - mongo
      - redis
    ports:
      - '127.0.0.1:8000:8000'

  worker:
    build:
      context: '.'
    command: celery worker -l info -A slabot.tasks
    depends_on:
      - api

volumes:
  redis-data:
  mongo-data:
