version: '3'

services:
  redis:
    image: redis
    volumes:
      - 'redis-data:/data'

  api:
    build:
      context: '.'
    depends_on:
      - redis
    ports:
      - '127.0.0.1:8000:8000'

  worker:
    build:
      context: '.'
    environment:
      - CELERY_BROKER_URL='redis://redis:6379/0'
    command: celery worker -B -l info -A slabot.tasks
    depends_on:
      - 'api'
      - 'redis'

volumes:
  redis-data:
